/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author Sudirwo
 */
public class HitungHariFrame extends javax.swing.JFrame {

    /**
     * Creates new form HitungHariFrame
     */
    public HitungHariFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBulan = new javax.swing.JComboBox<>();
        spinTahun = new javax.swing.JSpinner();
        btnHitung = new javax.swing.JButton();
        lblJumlahHari = new javax.swing.JLabel();
        lblHariPertama = new javax.swing.JLabel();
        lblHariTerakhir = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JCalendar();
        calendarAwal = new com.toedter.calendar.JDateChooser();
        calendarAkhir = new com.toedter.calendar.JDateChooser();
        btnSelisih = new javax.swing.JButton();
        lblSelisihHari = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Perhitungan Hari");
        jPanel1.add(jLabel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Bulan:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setText("Tahun:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel2.add(comboBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 230, -1));

        spinTahun.setModel(new javax.swing.SpinnerNumberModel(2024, 1, 9999, 1));
        jPanel2.add(spinTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 79, -1));

        btnHitung.setBackground(new java.awt.Color(102, 153, 255));
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel2.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 140, -1));

        lblJumlahHari.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblJumlahHari.setText("Jumlah Hari      : -");
        jPanel2.add(lblJumlahHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        lblHariPertama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHariPertama.setText("Hari Pertama   : -");
        jPanel2.add(lblHariPertama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        lblHariTerakhir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHariTerakhir.setText("Hari Terakhir    : -");
        jPanel2.add(lblHariTerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarPropertyChange(evt);
            }
        });
        jPanel2.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 600, 170));
        jPanel2.add(calendarAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 180, -1));
        jPanel2.add(calendarAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 180, -1));

        btnSelisih.setBackground(new java.awt.Color(102, 153, 255));
        btnSelisih.setForeground(new java.awt.Color(255, 255, 255));
        btnSelisih.setText("Hitung Selisih");
        btnSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelisihActionPerformed(evt);
            }
        });
        jPanel2.add(btnSelisih, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 180, -1));

        lblSelisihHari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSelisihHari.setText("Selisih Hari: -");
        jPanel2.add(lblSelisihHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Selisih Hari");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel7.setText("Pilih Tanggal :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel8.setText("Pilih Tanggal :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        hitungHari();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void calendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarPropertyChange
        // TODO add your handling code here:                                       
        sinkronDariCalendar();
       
    }//GEN-LAST:event_calendarPropertyChange

    private void btnSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelisihActionPerformed
        // TODO add your handling code here:
        hitungSelisihHari();
    }//GEN-LAST:event_btnSelisihActionPerformed

    private void hitungHari() {
        try {
            int bulan = comboBulan.getSelectedIndex() + 1;
            int tahun = (Integer) spinTahun.getValue();

            LocalDate tanggal = LocalDate.of(tahun, bulan, 1);

            int jumlahHari = tanggal.lengthOfMonth();
            String hariPertama = tanggal.getDayOfWeek().toString();
            String hariTerakhir = tanggal.withDayOfMonth(jumlahHari).getDayOfWeek().toString();

            lblJumlahHari.setText("Jumlah Hari: " + jumlahHari);
            lblHariPertama.setText("Hari Pertama: " + hariPertama);
            lblHariTerakhir.setText("Hari Terakhir: " + hariTerakhir);

        } catch (Exception e) {
            lblJumlahHari.setText("Error!");
        }
    }
    private void sinkronDariCalendar() {
        if (calendar.getDate() != null) {
            LocalDate ld = calendar.getDate().toInstant()
                    .atZone(ZoneId.systemDefault()).toLocalDate();
            int bulan = ld.getMonthValue();
            int tahun = ld.getYear();

            comboBulan.setSelectedIndex(bulan - 1);
            spinTahun.setValue(tahun); 
        }
    }
    private void hitungSelisihHari() {
        // 1. Cek apakah kedua tanggal sudah dipilih
        if (calendarAwal.getDate() == null || calendarAkhir.getDate() == null) {
            lblSelisihHari.setText("Pilih kedua tanggal!");
            return;
        }

        // 2. Konversi dengan aman
        LocalDate t1 = calendarAwal.getDate().toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate t2 = calendarAkhir.getDate().toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();

        // 3. Hitung selisih
        long selisih = ChronoUnit.DAYS.between(t1, t2);

        // 4. Tampilkan (Gunakan Math.abs jika ingin selisih selalu positif)
        lblSelisihHari.setText("Selisih Hari: " + Math.abs(selisih) + " hari");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitungHariFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSelisih;
    private com.toedter.calendar.JCalendar calendar;
    private com.toedter.calendar.JDateChooser calendarAkhir;
    private com.toedter.calendar.JDateChooser calendarAwal;
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHariPertama;
    private javax.swing.JLabel lblHariTerakhir;
    private javax.swing.JLabel lblJumlahHari;
    private javax.swing.JLabel lblSelisihHari;
    private javax.swing.JSpinner spinTahun;
    // End of variables declaration//GEN-END:variables
}
